# Generated by Django 6.0 on 2026-01-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='couverture/')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
