# Generated by Django 6.0 on 2026-01-22 09:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_livre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chap', models.IntegerField()),
                ('titre_chap', models.CharField(max_length=50)),
                ('contenu', ckeditor.fields.RichTextField()),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='profiles.livre')),
            ],
        ),
    ]
