# Generated by Django 6.0 on 2026-01-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_livre_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
