# Generated by Django 6.0 on 2026-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_livre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
