# Generated by Django 6.0 on 2026-01-25 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_livre_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='livres_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livre',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='livres_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livre',
            name='vues',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
