# Generated by Django 6.0 on 2026-01-25 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_livre_likes_livre_saves_livre_vues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='vues',
        ),
        migrations.AddField(
            model_name='livre',
            name='lires',
            field=models.ManyToManyField(blank=True, related_name='livres_lires', to=settings.AUTH_USER_MODEL),
        ),
    ]
