# Generated by Django 6.0 on 2026-01-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_livre_vues_livre_lires'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='vues',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
